volumes:
  dbdata:

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: checkins
      POSTGRES_USER: checkins
      POSTGRES_PASSWORD: checkins
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: ghcr.io/chriskacerguis/checkins:latest
    environment:
      NODE_ENV: production
      PORT: 3000
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: checkins
      PGUSER: checkins
      PGPASSWORD: checkins
      SSL_KEY_PATH: /app/ssl/key.pem
      SSL_CERT_PATH: /app/ssl/cert.pem
      FORCE_HTTPS: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - key.pem:/app/ssl/key.pem
      - cert.pem:/app/ssl/cert.pem
