version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: checkins
      POSTGRES_USER: checkins
      POSTGRES_PASSWORD: checkins
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    environment:
      NODE_ENV: development
      PORT: 3000
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: checkins
      PGUSER: checkins
      PGPASSWORD: checkins
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./:/app

volumes:
  dbdata:
