name: Docker publish (GHCR)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]     # e.g. v1.2.3
  pull_request:
    branches: [ "main" ]

# Needed to push to GHCR with the built-in GITHUB_TOKEN
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  # Image name == <registry>/<owner>/<repo>, lowercase per GHCR rules
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build & (conditionally) push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/\${{ env.IMAGE_NAME }}
          # Generate smart tags:
          # - On tags: use the tag (e.g. v1.2.3) and 'latest'
          # - On main: tag with 'edge' and the short SHA
          # - On PRs: tag with 'pr-<num>' and SHA (no push)
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=edge,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha,format=short
            type=ref,event=pr
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=${{ github.repository }}
            org.opencontainers.image.description=Container image for ${{ github.repository }}

      - name: Build (and push when not PR)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          # Multi-arch image (optional; comment out if you only need linux/amd64)
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # You can pass build args if your Dockerfile uses them
          build-args: |
            NODE_ENV=production
